# Basic
title: NeptuneChen
subtitle: 大道之行也，天下为公
welcome_message: 欢迎来到我的个人网站! 
description: Hi,我是NeptuneChen,一名小小的前端爱好者,目前还在自学,致力于web前端的研究和应用,努力成为一名优秀的前端开发工程师。
creator: <a href="http://www.NeptuneChen.top">@NeptuneChen</a>

url: "http://www.neptunechen.top"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: GitHub,     in_site: false,  description: NeptuneChen's GitHub,    url: 'https://github.com/NeptuneChen'}
    - {title: cnblogs,     in_site: false,  description: NeptuneChen's cnblogs,    url: 'http://www.cnblogs.com/NeptuneChen'}
    - {title: Projects, description: My Projects, url: 'http://www.neptunechen.top/wjs/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: NeptuneChen
    # duoshuo: 
    
# Social
social:
    weibo: chenghaihuang
    github: NeptuneChen
    twitter:  
    gplus:  
    mail: 1777155@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
