# Basic
title: NeptuneChen
subtitle: 大道之行也，天下为公。
welcome_message: 欢迎来到我的个人网站做客! 
description: Hi,我是NeptuneChen,一名小小的前端爱好者,目前还在自学,致力于web前端的研究和应用,努力成为一名优秀的前端开发工程师。
creator: <a href="http://www.NeptuneChen.top">@NeptuneChen</a>

url: "http://www.neptunechen.top"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: NeptuneChen's GitHub,    url: 'https://github.com/GcsSloop'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 NeptuneChen,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: NeptuneChen
    # duoshuo:
# Social
social:
    weibo: NeptuneChen
    github: NeptuneChen
    twitter: NeptuneChen
    rss: /feed.xml
    mail: 1777155@qq.com
    copyright: http://choosealicense.online

# Google Analytics
ga:
    # id: UA-82493667-1
    host: www.NeptuneChen.top
Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Terms Privacy Security Status Help
